In [2]:
from sklearn import datasets, linear_model
# Conjunto de datos de diabetes
X, y = datasets.load_diabetes(return_X_y=True)

In [3]:
diabetes = datasets.load_diabetes()

In [4]:
type(diabetes)

sklearn.utils._bunch.Bunch

In [ ]:
print(diabetes.target[:10])
print(diabetes.DESCR)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310.]
.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s

In [5]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
linear_regressor = LinearRegression()

In [17]:
cv_results = cross_validate(linear_regressor, X, y, cv=3,scoring = ["neg_mean_squared_error","r2"], return_estimator=True,return_train_score=True)
print(sorted(cv_results.keys()))
print(cv_results['train_neg_mean_squared_error'].mean())
print(cv_results['test_neg_mean_squared_error'])

['estimator', 'fit_time', 'score_time', 'test_neg_mean_squared_error', 'test_r2', 'train_neg_mean_squared_error', 'train_r2']
-2553.9739424267477
[-2727.76167002 -3481.83503879 -3524.6558219 ]


In [14]:
print(cv_results)

{'fit_time': array([0.00163651, 0.00842929, 0.00200653]), 'score_time': array([0.01284742, 0.00194287, 0.00164437]), 'estimator': [LinearRegression(), LinearRegression(), LinearRegression()], 'test_neg_mean_squared_error': array([-2727.76167002, -3481.83503879, -3524.6558219 ]), 'train_neg_mean_squared_error': array([-2784.60579691, -2426.16776496, -2451.14826541]), 'test_r2': array([0.49842308, 0.10377707, 0.44394205]), 'train_r2': array([0.51596751, 0.60652904, 0.48251836])}


## K Fold

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)
print(kf)
for i, (train_index, test_index) in enumerate(kf.split(X)):
    print(f"Fold {i}:")
    print(f"  Train: index={train_index}")
    print(f"  Test:  index={test_index}")

KFold(n_splits=2, random_state=None, shuffle=False)
Fold 0:
  Train: index=[2 3]
  Test:  index=[0 1]
Fold 1:
  Train: index=[0 1]
  Test:  index=[2 3]


In [ ]:
import numpy as np
from sklearn.model_selection import KFold

X = ["a", "b", "c", "d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):
    print("%s %s" % (train, test))

[2 3] [0 1]
[0 1] [2 3]


In [ ]:
X = np.array([[0., 0], [1., 1.], [-1., -1.], [2., 2.]])
y = np.array([0, 1, 0, 1])
X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]

In [ ]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0. 0.]
 [1. 1.]]
[[-1. -1.]
 [ 2.  2.]]
[0 1]
[0 1]
